### ISSUE TITLE
Attachments

### ISSUE THREAD

**Issue by jalevin** [tghanem/pst#1] opened 2019-08-28 00:41 UTC
I'm running into an issue trying to extract attachments from a pst. I converted the project to a dotnetcore 2.1 app. Any ideas where I might be able start tracking this down or if this was working prior to converting to dotnet core?

/usr/local/share/dotnet/dotnet /Users//projects//PST/pst/pstExploder/bin/Debug/netcoreapp2.1/pstExploder.dll
Recursing Subfolders of: Deleted Items
scan messages took: 17.618ms
Recursing Subfolders of: Search Results

Unhandled Exception: System.InvalidOperationException: Sequence contains no matching element
   at System.Linq.Enumerable.First[TSource](IEnumerable`1 source, Func`2 predicate)
   at pst.interfaces.ndb.NodeEntry.GetChildOfType(Int32 type) in /Users//projects//PST/pst/pst/interfaces/ndb/NodeEntry.cs:line 24
   at pst.Message.LoadPreExistingAttachments() in /Users//projects//PST/pst/pst/Message.cs:line 112
   at pst.Message.GetAttachments() in /Users//projects//PST/pst/pst/Message.cs:line 79

**Comment by timothyghanim** [comment] 2019-08-28 06:43
I don't think that the target framework has anything to do with this because the library uses standard APIs that should exist everywhere.

Now, regarding your issue, can you please create a simple PST file that contains a message with identical structure to the real one and send it over? If you can't, then can you please describe the minimum PST and message structure to reproduce this problem?

**Comment by timothyghanim** [comment] 2019-12-23 08:52
I'll close this for now until I hear back.

**Closed as completed by timothyghanim** 2019-12-23 08:52 UTC
